services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: surge-radarr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - ${STORAGE_PATH}/Radarr/config:/config
      - ${STORAGE_PATH}/Radarr/media:/movies
      - ${STORAGE_PATH}/Radarr/downloads:/downloads
    ports:
      - "${RADARR_PORT:-7878}:7878"
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: surge-sonarr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - ${STORAGE_PATH}/Sonarr/config:/config
      - ${STORAGE_PATH}/Sonarr/media:/tv
      - ${STORAGE_PATH}/Sonarr/downloads:/downloads
    ports:
      - "${SONARR_PORT:-8989}:8989"
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: surge-bazarr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - ${STORAGE_PATH}/Bazarr/config:/config
      - ${STORAGE_PATH}/Bazarr/media/movies:/movies
      - ${STORAGE_PATH}/Bazarr/media/tv:/tv
    ports:
      - "${BAZARR_PORT:-6767}:6767"
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network
    profiles:
      - bazarr

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: surge-prowlarr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - ${STORAGE_PATH}/Prowlarr/config:/config
      - ./configs/prowlarr/indexers:/config/Definitions/Custom
    ports:
      - "${PROWLARR_PORT:-9696}:9696"
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network

  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: surge-nzbget
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
      - NZBGET_USER=${NZBGET_USER:-admin}
      - NZBGET_PASS=${NZBGET_PASS:-tegbzn6789}
    volumes:
      - ${STORAGE_PATH}/NZBGet/config:/config
      - ${STORAGE_PATH}/NZBGet/downloads:/downloads
    ports:
      - "${NZBGET_PORT:-6789}:6789"
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network
    profiles:
      - nzbget

  rdt-client:
    image: rogerfar/rdtclient:latest
    container_name: surge-rdt-client
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - ${STORAGE_PATH}/RDT-Client/config:/data/db
      - ${STORAGE_PATH}/RDT-Client/downloads:/data/downloads
    ports:
      - "${RDT_CLIENT_PORT:-6500}:6500"
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network
    profiles:
      - rdt-client

  zurg:
    image: ghcr.io/debridmediamanager/zurg-testing:latest
    container_name: surge-zurg
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
      - ZURG_DOWNLOADS_PATH=${ZURG_DOWNLOADS_PATH:-/downloads}
    volumes:
      - ${STORAGE_PATH}/Zurg/config:/app/config
      - ${STORAGE_PATH}/downloads/Zurg:/data:shared
    ports:
      - "${ZURG_PORT:-9999}:9999"
    restart: ${RESTART_POLICY:-unless-stopped}
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
    security_opt:
      - apparmor:unconfined
    networks:
      - surge-network
    profiles:
      - zurg

  cli-debrid:
    image: godver3/cli_debrid:latest
    container_name: surge-cli-debrid
    ports:
      - "${CLI_DEBRID_PORT:-5000}:5000"
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
      - RD_API_KEY=${RD_API_TOKEN}
      - AD_API_KEY=${AD_API_TOKEN:-}
      - PREMIUMIZE_API_KEY=${PREMIUMIZE_API_TOKEN:-}
    volumes:
      - ${STORAGE_PATH}/cli_debrid/config:/app/config
      - ${STORAGE_PATH}/cli_debrid/downloads:/downloads
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network
    profiles:
      - cli-debrid

  decypharr:
    image: cy01/blackhole:latest
    container_name: surge-decypharr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - ${STORAGE_PATH}/Decypharr/config:/app/config
      - ${STORAGE_PATH}/Decypharr/downloads:/mnt/downloads
      - ${STORAGE_PATH}/Decypharr/movies:/mnt/movies
      - ${STORAGE_PATH}/Decypharr/tv:/mnt/tv
    ports:
      - "${DECYPHARR_PORT:-8282}:8282"
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network
    profiles:
      - decypharr

  posterizarr:
    image: ghcr.io/fscorrupt/posterizarr:latest
    container_name: surge-posterizarr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - ${STORAGE_PATH}/Posterizarr/config:/config
      - ${STORAGE_PATH}/Posterizarr/assets:/assets
      - ${STORAGE_PATH}/Posterizarr/logs:/logs
      - ${STORAGE_PATH}/Posterizarr/movies:/movies
      - ${STORAGE_PATH}/Posterizarr/tv:/tv
    ports:
      - "${POSTERIZARR_PORT:-5060}:5060"
    restart: "no"
    networks:
      - surge-network
    profiles:
      - posterizarr

  cinesync:
    image: sureshfizzy/cinesync:latest
    container_name: surge-cinesync
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
      # Directory Paths
      - SOURCE_DIR=${CINESYNC_SOURCE_DIR:-${STORAGE_PATH}/downloads/Zurg/__all__}
      - DESTINATION_DIR=${CINESYNC_DESTINATION_DIR:-${STORAGE_PATH}/media}
      - USE_SOURCE_STRUCTURE=${CINESYNC_USE_SOURCE_STRUCTURE:-false}
      # Media Organization Configuration
      - CINESYNC_LAYOUT=${CINESYNC_LAYOUT:-true}
      - ANIME_SEPARATION=${CINESYNC_ANIME_SEPARATION:-true}
      - 4K_SEPARATION=${CINESYNC_4K_SEPARATION:-false}
      - KIDS_SEPARATION=${CINESYNC_KIDS_SEPARATION:-false}
      # Custom folder paths
      - CUSTOM_SHOW_FOLDER=${CINESYNC_CUSTOM_SHOW_FOLDER:-TV Series}
      - CUSTOM_4KSHOW_FOLDER=${CINESYNC_CUSTOM_4KSHOW_FOLDER:-4K Series}
      - CUSTOM_ANIME_SHOW_FOLDER=${CINESYNC_CUSTOM_ANIME_SHOW_FOLDER:-Anime Series}
      - CUSTOM_MOVIE_FOLDER=${CINESYNC_CUSTOM_MOVIE_FOLDER:-Movies}
      - CUSTOM_4KMOVIE_FOLDER=${CINESYNC_CUSTOM_4KMOVIE_FOLDER:-4K Movies}
      - CUSTOM_ANIME_MOVIE_FOLDER=${CINESYNC_CUSTOM_ANIME_MOVIE_FOLDER:-Anime Movies}
      - CUSTOM_KIDS_MOVIE_FOLDER=${CINESYNC_CUSTOM_KIDS_MOVIE_FOLDER:-Kids Movies}
      - CUSTOM_KIDS_SHOW_FOLDER=${CINESYNC_CUSTOM_KIDS_SHOW_FOLDER:-Kids Series}
      # Resolution-Based Organization
      - SHOW_RESOLUTION_STRUCTURE=${CINESYNC_SHOW_RESOLUTION_STRUCTURE:-false}
      - MOVIE_RESOLUTION_STRUCTURE=${CINESYNC_MOVIE_RESOLUTION_STRUCTURE:-false}
      # Logging Configuration
      - LOG_LEVEL=${CINESYNC_LOG_LEVEL:-INFO}
      # Rclone Mount Configuration
      - RCLONE_MOUNT=${CINESYNC_RCLONE_MOUNT:-false}
      - MOUNT_CHECK_INTERVAL=${CINESYNC_MOUNT_CHECK_INTERVAL:-30}
      # TMDb/IMDB Configuration
      - TMDB_API_KEY=${CINESYNC_TMDB_API_KEY:-${TMDB_API_KEY}}
      - LANGUAGE=${CINESYNC_LANGUAGE:-English}
      - ANIME_SCAN=${CINESYNC_ANIME_SCAN:-false}
      - TMDB_FOLDER_ID=${CINESYNC_TMDB_FOLDER_ID:-false}
      - IMDB_FOLDER_ID=${CINESYNC_IMDB_FOLDER_ID:-false}
      - TVDB_FOLDER_ID=${CINESYNC_TVDB_FOLDER_ID:-false}
      - RENAME_ENABLED=${CINESYNC_RENAME_ENABLED:-false}
      - MEDIAINFO_PARSER=${CINESYNC_MEDIAINFO_PARSER:-false}
      - RENAME_TAGS=${CINESYNC_RENAME_TAGS:-Resolution}
      # Movie Collection Settings
      - MOVIE_COLLECTION_ENABLED=${CINESYNC_MOVIE_COLLECTION_ENABLED:-false}
      # System Configuration
      - RELATIVE_SYMLINK=${CINESYNC_RELATIVE_SYMLINK:-false}
      - MAX_CORES=${CINESYNC_MAX_CORES:-1}
      - MAX_PROCESSES=${CINESYNC_MAX_PROCESSES:-15}
      # File Handling Configuration
      - SKIP_EXTRAS_FOLDER=${CINESYNC_SKIP_EXTRAS_FOLDER:-true}
      - JUNK_MAX_SIZE_MB=${CINESYNC_JUNK_MAX_SIZE_MB:-5}
      - ALLOWED_EXTENSIONS=${CINESYNC_ALLOWED_EXTENSIONS:-.mp4,.mkv,.srt,.avi,.mov,.divx,.strm}
      - SKIP_ADULT_PATTERNS=${CINESYNC_SKIP_ADULT_PATTERNS:-true}
      # Real-Time Monitoring Configuration
      - SLEEP_TIME=${CINESYNC_SLEEP_TIME:-60}
      - SYMLINK_CLEANUP_INTERVAL=${CINESYNC_SYMLINK_CLEANUP_INTERVAL:-600}
      # Plex Integration Configuration
      - ENABLE_PLEX_UPDATE=${CINESYNC_ENABLE_PLEX_UPDATE:-false}
      - PLEX_URL=${CINESYNC_PLEX_URL:-http://localhost:32400}
      - PLEX_TOKEN=${CINESYNC_PLEX_TOKEN:-}
      # CineSync Server Configuration
      - CINESYNC_IP=${CINESYNC_IP:-0.0.0.0}
      - CINESYNC_API_PORT=${CINESYNC_API_PORT:-8082}
      - CINESYNC_UI_PORT=${CINESYNC_UI_PORT:-5173}
      - CINESYNC_AUTH_ENABLED=${CINESYNC_AUTH_ENABLED:-true}
      - CINESYNC_USERNAME=${CINESYNC_USERNAME:-admin}
      - CINESYNC_PASSWORD=${CINESYNC_PASSWORD:-admin}
      # MediaHub Service Configuration
      - MEDIAHUB_AUTO_START=${CINESYNC_MEDIAHUB_AUTO_START:-true}
      - RTM_AUTO_START=${CINESYNC_RTM_AUTO_START:-false}
      - FILE_OPERATIONS_AUTO_MODE=${CINESYNC_FILE_OPERATIONS_AUTO_MODE:-true}
      # Database Configuration
      - DB_THROTTLE_RATE=${CINESYNC_DB_THROTTLE_RATE:-100}
      - DB_MAX_RETRIES=${CINESYNC_DB_MAX_RETRIES:-10}
      - DB_RETRY_DELAY=${CINESYNC_DB_RETRY_DELAY:-1.0}
      - DB_BATCH_SIZE=${CINESYNC_DB_BATCH_SIZE:-1000}
      - DB_MAX_WORKERS=${CINESYNC_DB_MAX_WORKERS:-20}
    ports:
      - "${CINESYNC_PORT:-8082}:8082"
      - "${CINESYNC_DEV_PORT:-5173}:5173"
    volumes:
      - ${STORAGE_PATH}/Cinesync/config:/config
      - ${STORAGE_PATH}/Cinesync/config/.env:/app/.env:ro
      - ${STORAGE_PATH}/downloads:/downloads
      - ${STORAGE_PATH}/media:/media
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network
    profiles:
      - cinesync

  placeholdarr:
    image: ghcr.io/theindiearmy/placeholdarr:queue_monitoring-latest
    container_name: surge-placeholdarr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - ${STORAGE_PATH}/Placeholdarr/config:/config
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network

  overseerr:
    image: sctx/overseerr:latest
    container_name: surge-overseerr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - ${STORAGE_PATH}/Overseerr/config:/app/config
    ports:
      - "${OVERSEERR_PORT:-5055}:5055"
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: surge-tautulli
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - ${STORAGE_PATH}/Tautulli/config:/config
    ports:
      - "${TAUTULLI_PORT:-8182}:8181"
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network
    profiles:
      - tautulli

  gaps:
    image: housewrecker/gaps:latest
    container_name: surge-gaps
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
      - ENABLE_SSL=false
      - ENABLE_LOGIN=false
      - BASE_URL=
    volumes:
      - ${STORAGE_PATH}/GAPS/config:/usr/data
    ports:
      - "8484:8484"
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network
    profiles:
      - gaps

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: surge-homepage
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - ${STORAGE_PATH}/Homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "${HOMEPAGE_PORT:-3000}:3000"
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network

  watchtower:
    image: containrrr/watchtower:latest
    container_name: surge-watchtower
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=${WATCHTOWER_INTERVAL:-86400}
      - WATCHTOWER_NOTIFICATION_URL=${WATCHTOWER_WEBHOOK:-}
      - WATCHTOWER_NOTIFICATIONS_LEVEL=info
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network
    profiles:
      - watchtower

  scheduler:
    image: crazymax/cron:latest
    container_name: surge-scheduler
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - ${STORAGE_PATH}/Scheduler/config:/config
      - ${STORAGE_PATH}/logs:/logs
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scripts:/scripts:ro
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network
    profiles:
      - scheduler

  pd_zurg:
    image: iampuid0/pd_zurg:2.5.0
    container_name: surge-pd_zurg
    stdin_open: true
    tty: true
    environment:
      - TZ=${TZ:-UTC}
      - ZURG_ENABLED=true
      - RD_API_KEY=${RD_API_TOKEN}
      - RCLONE_MOUNT_NAME=pd_zurg
    volumes:
      - ${STORAGE_PATH}/pd_zurg/config:/config
      - ${STORAGE_PATH}/pd_zurg/log:/log
      - ${STORAGE_PATH}/pd_zurg/cache:/cache
      - ${STORAGE_PATH}/pd_zurg/RD:/zurg/RD
      - ${STORAGE_PATH}/downloads/pd_zurg:/data:shared
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network

networks:
  surge-network:
    name: surge-network