services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: surge-radarr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - ${STORAGE_PATH}/Radarr/config:/config
      - ${STORAGE_PATH}/Radarr/downloads:/downloads
    ports:
      - "${RADARR_PORT:-7878}:7878"
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network
    profiles:
      - radarr

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: surge-sonarr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - ${STORAGE_PATH}/Sonarr/config:/config
      - ${STORAGE_PATH}/Sonarr/downloads:/downloads
    ports:
      - "${SONARR_PORT:-8989}:8989"
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network
    profiles:
      - sonarr

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: surge-bazarr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - ${STORAGE_PATH}/Bazarr/config:/config
    ports:
      - "${BAZARR_PORT:-6767}:6767"
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network
    profiles:
      - bazarr

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: surge-prowlarr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - ${STORAGE_PATH}/Prowlarr/config:/config
      - ./configs/prowlarr/indexers:/config/Definitions/Custom
    ports:
      - "${PROWLARR_PORT:-9696}:9696"
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network
    profiles:
      - prowlarr

  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: surge-nzbget
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
      - NZBGET_USER=${NZBGET_USER:-admin}
      - NZBGET_PASS=${NZBGET_PASS:-password}
    volumes:
      - ${STORAGE_PATH}/NZBGet/config:/config
      - ${STORAGE_PATH}/NZBGet/downloads:/downloads
    ports:
      - "${NZBGET_PORT:-6789}:6789"
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network
    profiles:
      - nzbget

  cli-debrid:
    image: godver3/cli_debrid:latest
    container_name: surge-cli-debrid
    ports:
      - "${CLI_DEBRID_PORT:-5000}:5000"
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
      - RD_API_KEY=${RD_API_TOKEN}
      - AD_API_KEY=${AD_API_TOKEN:-}
      - PREMIUMIZE_API_KEY=${PREMIUMIZE_API_TOKEN:-}
    volumes:
      - ${STORAGE_PATH}/cli_debrid/config:/app/config
      - ${STORAGE_PATH}/cli_debrid/downloads:/downloads
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network
    profiles:
      - cli-debrid

  decypharr:
    image: cy01/blackhole:latest
    container_name: surge-decypharr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
      - RD_API_TOKEN=${RD_API_TOKEN}
      - AD_API_TOKEN=${AD_API_TOKEN:-}
      - DEBRID_LINK_API_TOKEN=${DEBRID_LINK_API_TOKEN:-}
      - TORBOX_API_TOKEN=${TORBOX_API_TOKEN:-}
    volumes:
      - ${STORAGE_PATH}/Decypharr/config:/app/config
      - ${STORAGE_PATH}/Decypharr/config/config.json:/app/config.json
      - ${STORAGE_PATH}/Decypharr:/media/remote/realdebrid/__all__/
      - ${STORAGE_PATH}/Decypharr/symlinks:/mnt/downloads/symlinks
      - ${STORAGE_PATH}/Decypharr/temp:/mnt/downloads/temp
      - ${STORAGE_PATH}/Decypharr/remote:/mnt/rclone/remote
      - ${STORAGE_PATH}/Decypharr/cache:/mnt/rclone/cache
      - ${STORAGE_PATH}/downloads/Decypharr/blackhole/sonarr:/mnt/downloads/blackhole/sonarr
      - ${STORAGE_PATH}/downloads/Decypharr/blackhole/radarr:/mnt/downloads/blackhole/radarr
      - ${STORAGE_PATH}/downloads/Decypharr/debrids/realdebrid:/mnt/rclone/remote/realdebrid:rshared
      - ${STORAGE_PATH}/downloads/Decypharr/debrids/alldebrid:/mnt/rclone/remote/alldebrid:rshared
      - ${STORAGE_PATH}/downloads/Decypharr/debrids/debridlink:/mnt/rclone/remote/debridlink:rshared
      - ${STORAGE_PATH}/downloads/Decypharr/debrids/torbox:/mnt/rclone/remote/torbox:rshared

    ports:
      - "${DECYPHARR_PORT:-8282}:8282"
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network
    profiles:
      - decypharr
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
    security_opt:
      - apparmor:unconfined

  posterizarr:
    image: ghcr.io/fscorrupt/posterizarr:latest
    container_name: surge-posterizarr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - ${STORAGE_PATH}/Posterizarr/config:/config
      - ${STORAGE_PATH}/Posterizarr/assets:/assets
      - ${STORAGE_PATH}/Posterizarr/logs:/logs
    ports:
      - "${POSTERIZARR_PORT:-5060}:5060"
    restart: "no"
    networks:
      - surge-network
    profiles:
      - posterizarr

  cinesync:
    image: sureshfizzy/cinesync:latest
    container_name: surge-cinesync
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    ports:
      - "${CINESYNC_PORT:-8082}:8082"
      - "${CINESYNC_DEV_PORT:-5173}:5173"
    volumes:
      - ${STORAGE_PATH}/CineSync/config/.env:/app/.env
      - ${STORAGE_PATH}/downloads:/downloads
      - /mnt:/mnt
      - ${STORAGE_PATH}:${STORAGE_PATH}
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network
    profiles:
      - cinesync

  placeholdarr:
    image: ghcr.io/theindiearmy/placeholdarr:queue_monitoring-latest
    container_name: surge-placeholdarr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - ${STORAGE_PATH}/Placeholdarr/config:/config
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network
    profiles:
      - placeholdarr

  overseerr:
    image: sctx/overseerr:latest
    container_name: surge-overseerr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - ${STORAGE_PATH}/Overseerr/config:/app/config
    ports:
      - "${OVERSEERR_PORT:-5055}:5055"
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network
    profiles:
      - overseerr

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: surge-tautulli
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - ${STORAGE_PATH}/Tautulli/config:/config
    ports:
      - "${TAUTULLI_PORT:-8182}:8181"
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network
    profiles:
      - tautulli

  gaps:
    image: housewrecker/gaps:latest
    container_name: surge-gaps
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
      - ENABLE_SSL=false
      - ENABLE_LOGIN=false
      - BASE_URL=
    volumes:
      - ${STORAGE_PATH}/GAPS/config:/usr/data
    ports:
      - "8484:8484"
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network
    profiles:
      - gaps

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: surge-homepage
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - ${STORAGE_PATH}/Homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "${HOMEPAGE_PORT:-3000}:3000"
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network
    profiles:
      - homepage

  watchtower:
    image: containrrr/watchtower:latest
    container_name: surge-watchtower
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=${WATCHTOWER_INTERVAL:-86400}
      - WATCHTOWER_NOTIFICATION_URL=${WATCHTOWER_WEBHOOK:-}
      - WATCHTOWER_NOTIFICATIONS_LEVEL=info
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network
    profiles:
      - watchtower

networks:
  surge-network:
    name: surge-network