services:
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: surge-tautulli
    volumes:
      - ${STORAGE_PATH}/Tautulli/config:/config
    restart: unless-stopped
    networks:
      - surge-network
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: surge-bazarr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - ${STORAGE_PATH}/Bazarr/config:/config
      - ${STORAGE_PATH}/Bazarr/media/movies:/movies
      - ${STORAGE_PATH}/Bazarr/media/tv:/tv
    ports:
      - "${BAZARR_PORT:-6767}:6767"
    restart: unless-stopped
    networks:
      - surge-network
  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: surge-nzbget
    volumes:
      - ${STORAGE_PATH}/NZBGet/config:/config
    restart: unless-stopped
    networks:
      - surge-network
  gaps:
    image: housewrecker/gaps:latest
    container_name: surge-gaps
    volumes:
      - ${STORAGE_PATH}/GAPS/config:/config
    restart: unless-stopped
    networks:
      - surge-network
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: surge-prowlarr
    volumes:
      - ${STORAGE_PATH}/Prowlarr/config:/config
    restart: unless-stopped
    networks:
      - surge-network
  overseerr:
    image: sctx/overseerr:latest
    container_name: surge-overseerr
    volumes:
      - ${STORAGE_PATH}/Overseerr/config:/config
    restart: unless-stopped
    networks:
      - surge-network
  posterizarr:
    image: ghcr.io/fscorrupt/posterizarr:latest
    container_name: surge-posterizarr
    volumes:
      - ${STORAGE_PATH}/Posterizarr/config:/config
    restart: unless-stopped
    networks:
      - surge-network
  kometa:
    image: kometateam/kometa:latest
    container_name: surge-kometa
    volumes:
      - ${STORAGE_PATH}/Kometa/config:/config
    restart: unless-stopped
    networks:
      - surge-network
networks:
  surge-network:
    name: surge-network
    driver: bridge
