
# ===========================================
# JELLYFIN MEDIA SERVER CONFIGURATION
# ===========================================

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: surge-jellyfin
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_PUBLISHED_SERVER_URL:-}
    volumes:
      - ${STORAGE_PATH}/Jellyfin/config:/config
      - ${STORAGE_PATH}/Jellyfin/cache:/cache
    ports:
      - "${JELLYFIN_PORT:-8096}:8096"
      - "8920:8920" # HTTPS
      - "7359:7359/udp" # Auto-discovery
      - "1900:1900/udp" # DLNA
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network
    devices:
      - /dev/dri:/dev/dri # For hardware transcoding (if available)
    profiles:
      - jellyfin
  # The following volumes are replaced with explicit host paths
