
# ===========================================
# PLEX MEDIA SERVER CONFIGURATION
# ===========================================

services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: surge-plex
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
      - PLEX_CLAIM=${PLEX_CLAIM:-}
      - ADVERTISE_IP=${PLEX_ADVERTISE_IP:-}
      - HOSTNAME=SurgePlex
    volumes:
      - plex-config:/config
      - plex-transcode:/transcode
      - shared-assets:/config/Library/Application Support/Plex Media Server/Metadata/Assets
      - ${MOVIES_DIR:-./data/media/movies}:/data/movies
      - ${TV_SHOWS_DIR:-./data/media/tv}:/data/tv
      - ${MUSIC_DIR:-./data/media/music}:/data/music
    ports:
      - "${PLEX_PORT:-32400}:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network
    devices:
      - /dev/dri:/dev/dri # For hardware transcoding (if available)
    profiles:
      - plex

volumes:
  plex-config:
  plex-transcode:
  shared-assets:  # Reference to shared volume from main compose
