services:
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: surge-tautulli
    volumes:
      - ${STORAGE_PATH}/Tautulli/config:/config
    restart: unless-stopped
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: surge-bazarr
    volumes:
      - ${STORAGE_PATH}/Bazarr/config:/config
    restart: unless-stopped
  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: surge-nzbget
    volumes:
      - ${STORAGE_PATH}/NZBGet/config:/config
    restart: unless-stopped
  gaps:
    image: housewrecker/gaps:latest
    container_name: surge-gaps
    volumes:
      - ${STORAGE_PATH}/GAPS/config:/config
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: surge-prowlarr
    volumes:
      - ${STORAGE_PATH}/Prowlarr/config:/config
    restart: unless-stopped
  overseerr:
    image: sctx/overseerr:latest
    container_name: surge-overseerr
    volumes:
      - ${STORAGE_PATH}/Overseerr/config:/config
    restart: unless-stopped
  posterizarr:
    image: ghcr.io/fscorrupt/posterizarr:latest
    container_name: surge-posterizarr
    volumes:
      - ${STORAGE_PATH}/Posterizarr/config:/config
    restart: unless-stopped
  kometa:
    image: kometateam/kometa:latest
    container_name: surge-kometa
    volumes:
      - ${STORAGE_PATH}/Kometa/config:/config
    restart: unless-stopped
networks:
  surge-network:
    name: surge-network
    driver: bridge
