
# ===========================================
# PLEX MEDIA SERVER CONFIGURATION
# ===========================================

services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: surge-plex
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
      - PLEX_CLAIM=${PLEX_CLAIM:-}
      - ADVERTISE_IP=${PLEX_ADVERTISE_IP:-}
      - HOSTNAME=SurgePlex
    volumes:
      - ${STORAGE_PATH}/Plex/config:/config
      - ${STORAGE_PATH}/Plex/transcode:/transcode
      - ${STORAGE_PATH}/Plex/assets:/config/Library/Application Support/Plex Media Server/Metadata/Assets
      - ${STORAGE_PATH}/media/movies:/data/movies
      - ${STORAGE_PATH}/media/tv:/data/tv
      - ${STORAGE_PATH}/media/music:/data/music
    ports:
      - "${PLEX_PORT:-32400}:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network
    devices:
      - /dev/dri:/dev/dri # For hardware tranoding (if available)
    profiles:
      - plex


