services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: surge-radarr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - radarr-config:/config
      - ${MOVIES_DIR:-./data/media/movies}:/movies
      - ${DOWNLOADS_DIR:-./data/downloads}:/downloads
    ports:
      - "${RADARR_PORT:-7878}:7878"
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: surge-sonarr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - sonarr-config:/config
      - ${TV_SHOWS_DIR:-./data/media/tv}:/tv
      - ${DOWNLOADS_DIR:-./data/downloads}:/downloads
    ports:
      - "${SONARR_PORT:-8989}:8989"
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: surge-bazarr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - bazarr-config:/config
      - ${MOVIES_DIR:-./data/media/movies}:/movies
      - ${TV_SHOWS_DIR:-./data/media/tv}:/tv
    ports:
      - "${BAZARR_PORT:-6767}:6767"
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: surge-prowlarr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - prowlarr-config:/config
      - ./configs/prowlarr/indexers:/config/Definitions/Custom
    ports:
      - "${PROWLARR_PORT:-9696}:9696"
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network

  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: surge-nzbget
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
      - NZBGET_USER=${NZBGET_USER:-admin}
      - NZBGET_PASS=${NZBGET_PASS:-tegbzn6789}
    volumes:
      - nzbget-config:/config
      - ${DOWNLOADS_DIR:-./data/downloads}:/downloads
    ports:
      - "${NZBGET_PORT:-6789}:6789"
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network

  rdt-client:
    image: rogerfar/rdtclient:latest
    container_name: surge-rdt-client
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - rdt-client-config:/data/db
      - ${DOWNLOADS_DIR:-./data/downloads}:/data/downloads
    ports:
      - "${RDT_CLIENT_PORT:-6500}:6500"
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network

  zurg:
    image: ghcr.io/debridmediamanager/zurg-testing:latest
    container_name: surge-zurg
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - zurg-config:/app/config
      - ${DOWNLOADS_DIR:-./data/downloads}:/downloads
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network

  zilean:
    image: ipromknight/zilean:latest
    container_name: surge-zilean
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - zilean-config:/app/data
    ports:
      - "${ZILEAN_PORT:-8182}:8181"
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network

  cli-debrid:
    image: godver3/cli_debrid:latest
    container_name: surge-cli-debrid
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
      - RD_API_KEY=${RD_API_TOKEN}
      - AD_API_KEY=${AD_API_TOKEN:-}
      - PREMIUMIZE_API_KEY=${PREMIUMIZE_API_TOKEN:-}
    volumes:
      - cli-debrid-config:/app/config
      - ${DOWNLOADS_DIR:-./data/downloads}:/downloads
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network

  decypharr:
    image: sirrobot01/decypharr:latest
    container_name: surge-decypharr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - decypharr-config:/app/config
      - ${DOWNLOADS_DIR:-./data/downloads}:/mnt/downloads
      - ${MOVIES_DIR:-./data/media/movies}:/mnt/movies
      - ${TV_DIR:-./data/media/tv}:/mnt/tv
    ports:
      - "${DECYPHARR_PORT:-8282}:8282"
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network

  posterizarr:
    image: ghcr.io/fscorrupt/posterizarr:latest
    container_name: surge-posterizarr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - posterizarr-config:/config
      - shared-assets:/assets
      - shared-logs:/logs
      - ${MOVIES_DIR:-./data/media/movies}:/movies
      - ${TV_SHOWS_DIR:-./data/media/tv}:/tv
    ports:
      - "${POSTERIZARR_PORT:-5060}:5060"
    restart: "no"
    networks:
      - surge-network

  cinesync:
    image: sureshfizzy/cinesync:latest
    container_name: surge-cinesync
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - cinesync-config:/config
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network

  placeholdarr:
    image: theindlearmy/placeholdarr:latest
    container_name: surge-placeholdarr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - placeholdarr-config:/config
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network

  overseerr:
    image: sctx/overseerr:latest
    container_name: surge-overseerr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - overseerr-config:/app/config
    ports:
      - "${OVERSEERR_PORT:-5055}:5055"
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: surge-tautulli
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - tautulli-config:/config
    ports:
      - "${TAUTULLI_PORT:-8181}:8181"
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: surge-homepage
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - homepage-config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "${HOMEPAGE_PORT:-3000}:3000"
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network