services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: surge-radarr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - ${STORAGE_PATH}/Radarr/config:/config
      - ${STORAGE_PATH}/Radarr/media:/movies
      - ${STORAGE_PATH}/Radarr/downloads:/downloads
    ports:
      - "${RADARR_PORT:-7878}:7878"
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: surge-sonarr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - ${STORAGE_PATH}/Sonarr/config:/config
      - ${STORAGE_PATH}/Sonarr/media:/tv
      - ${STORAGE_PATH}/Sonarr/downloads:/downloads
    ports:
      - "${SONARR_PORT:-8989}:8989"
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: surge-bazarr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - ${STORAGE_PATH}/Bazarr/config:/config
      - ${STORAGE_PATH}/Bazarr/media/movies:/movies
      - ${STORAGE_PATH}/Bazarr/media/tv:/tv
    ports:
      - "${BAZARR_PORT:-6767}:6767"
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: surge-prowlarr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - ${STORAGE_PATH}/Prowlarr/config:/config
      - ./configs/prowlarr/indexers:/config/Definitions/Custom
    ports:
      - "${PROWLARR_PORT:-9696}:9696"
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network

  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: surge-nzbget
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
      - NZBGET_USER=${NZBGET_USER:-admin}
      - NZBGET_PASS=${NZBGET_PASS:-tegbzn6789}
    volumes:
      - ${STORAGE_PATH}/NZBGet/config:/config
      - ${STORAGE_PATH}/NZBGet/downloads:/downloads
    ports:
      - "${NZBGET_PORT:-6789}:6789"
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network

  rdt-client:
    image: rogerfar/rdtclient:latest
    container_name: surge-rdt-client
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - ${STORAGE_PATH}/RDT-Client/config:/data/db
      - ${STORAGE_PATH}/RDT-Client/downloads:/data/downloads
    ports:
      - "${RDT_CLIENT_PORT:-6500}:6500"
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network

  zurg:
    image: ghcr.io/debridmediamanager/zurg-testing:latest
    container_name: surge-zurg
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - ${STORAGE_PATH}/Zurg/config:/app/config
      - ${STORAGE_PATH}/Zurg/downloads:/downloads
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network

  zilean-db:
    image: postgres:16-alpine
    container_name: surge-zilean-db
    environment:
      - POSTGRES_DB=zilean
      - POSTGRES_USER=zilean
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=${TZ:-UTC}
    volumes:
      - ${STORAGE_PATH}/Zilean/db:/var/lib/postgresql/data
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network

  zilean:
    image: ipromknight/zilean:latest
    container_name: surge-zilean
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
      - ConnectionStrings__DefaultConnection=Host=surge-zilean-db;Database=zilean;Username=zilean;Password=${POSTGRES_PASSWORD}
    volumes:
      - ${STORAGE_PATH}/Zilean/config:/app/data
    ports:
      - "${ZILEAN_PORT:-8181}:8181"
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network
    depends_on:
      - zilean-db

  cli-debrid:
    image: godver3/cli_debrid:latest
    container_name: surge-cli-debrid
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
      - RD_API_KEY=${RD_API_TOKEN}
      - AD_API_KEY=${AD_API_TOKEN:-}
      - PREMIUMIZE_API_KEY=${PREMIUMIZE_API_TOKEN:-}
    volumes:
      - ${STORAGE_PATH}/cli_debrid/config:/app/config
      - ${STORAGE_PATH}/cli_debrid/downloads:/downloads
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network

  decypharr:
    image: cy01/blackhole:latest
    container_name: surge-decypharr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - ${STORAGE_PATH}/Decypharr/config:/app/config
      - ${STORAGE_PATH}/Decypharr/downloads:/mnt/downloads
      - ${STORAGE_PATH}/Decypharr/movies:/mnt/movies
      - ${STORAGE_PATH}/Decypharr/tv:/mnt/tv
    ports:
      - "${DECYPHARR_PORT:-8282}:8282"
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network

  posterizarr:
    image: ghcr.io/fscorrupt/posterizarr:latest
    container_name: surge-posterizarr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - ${STORAGE_PATH}/Posterizarr/config:/config
      - ${STORAGE_PATH}/Posterizarr/assets:/assets
      - ${STORAGE_PATH}/Posterizarr/logs:/logs
      - ${STORAGE_PATH}/Posterizarr/movies:/movies
      - ${STORAGE_PATH}/Posterizarr/tv:/tv
    ports:
      - "${POSTERIZARR_PORT:-5060}:5060"
    restart: "no"
    networks:
      - surge-network

  cinesync:
    image: sureshfizzy/cinesync:latest
    container_name: surge-cinesync
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - ${STORAGE_PATH}/Cinesync/config:/config
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network

  placeholdarr:
    image: ghcr.io/theindiearmy/placeholdarr:queue_monitoring-latest
    container_name: surge-placeholdarr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - ${STORAGE_PATH}/Placeholdarr/config:/config
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network

  overseerr:
    image: sctx/overseerr:latest
    container_name: surge-overseerr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - ${STORAGE_PATH}/Overseerr/config:/app/config
    ports:
      - "${OVERSEERR_PORT:-5055}:5055"
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: surge-tautulli
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - ${STORAGE_PATH}/Tautulli/config:/config
    ports:
      - "${TAUTULLI_PORT:-8182}:8181"
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: surge-homepage
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - ${STORAGE_PATH}/Homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "${HOMEPAGE_PORT:-3000}:3000"
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - surge-network

networks:
  surge-network:
    name: surge-network