version: '3.8'
services:
  webui-backend:
    build: ./backend
    container_name: surge-webui-backend
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
  webui-frontend:
    build: ./frontend
    container_name: surge-webui-frontend
    ports:
      - "3100:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped
    depends_on:
      - webui-backend
