services:
  webui-backend:
    build: ./backend
    container_name: surge-webui-backend
    ports:
      - "5001:5001"
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
      - FLASK_ENV=production
    restart: unless-stopped
    entrypoint: ["sh", "-c", "/app/copy_env.sh && exec python app.py"]
    volumes:
      - ../.env.example:/app/.env.example
  webui-frontend:
    build: ./frontend
    container_name: surge-webui-frontend
    ports:
      - "3100:3000"
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped
    depends_on:
      - webui-backend
